#! /bin/sh
GTK_IM_MODULE=ibus
QT_IM_MODULE=ibus
XMODIFIERS=@im=ibus 
setxkbmap -option compose:ralt
ibus-daemon -rxRd
feh --bg-fill /home/nathan/Documents/bg.png
# picom seems to make highlight dragging render better
picom  --backend glx &
polybar & # this has messy padding
dunst &
xmousepasteblock &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config border_width           	2
bspc config window_gap             	0
bspc config bottom_padding         	0
bspc config top_padding            	0
bspc config left_padding           	0
bspc config right_padding          	0
bspc config -m HDMI-1-0 top_padding	40

bspc config focused_border_color "#ffa0ff"
bspc config normal_border_color "#606090"
bspc config active_border_color "#a060a0"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

home

bspc monitor HDMI-0 -d PI PII PIII PIV PV
bspc monitor DisplayPort-1-2 -d SI SII SIII SIV SV
bspc monitor DP-0 -d SI SII SIII SIV SV

bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config focus_follows_pointer true
